library(DiffBind)
SampleID <- c("H3K27_untreated_1", "H3K27_untreated_2", "H3K27_treated_1", "H3K27_treated_2")
Tissue <- rep("MCF7", 4)
Factor <- rep("H3K27me3", 4)
Condition <- c("KDM5B_WT", "KDM5B_WT", "KDM5B_KO", "KDM5B_KO")
bamReads <- c("C:/Users/kayle/Box/Vertinolab/Ching-Hua Shih/Cut-and-Tag/VER00038.CnT_2021.10.21.PE.NovaSeq/H3K27me3/bamFiles/dedup/MCF7.H3K27me3.B.dedup.bam",
              "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/CutnTag_n_chip/Vertino lab data/VER00046 2021.11.17 Cut and Tag/bams/hg38_dedup/ZS1_19_MCF7_EV_H3K27me3.dedup.bam",
              "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/CutnTag_n_chip/Vertino lab data/VER00046 2021.11.17 Cut and Tag/bams/hg38_dedup/ZS1_19_MCF7_SH1_H3K27me3.dedup.bam",
              "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/CutnTag_n_chip/Vertino lab data/VER00046 2021.11.17 Cut and Tag/bams/hg38_dedup/ZS1_19_MCF7_SH2_H3K27me3.dedup.bam")
Peaks <- c("MCF7.H3K27me3.B.AUC.stringent.bed", "ZS1_19_MCF7_EV_H3K27me3.stringent.bed",
         "ZS1_19_MCF7_SH1_H3K27me3.stringent.bed", "ZS1_19_MCF7_SH2_H3K27me3.stringent.bed")
mysampleSheet = cbind(SampleID, Tissue, Factor, Condition, bamReads, Peaks)
mysampleSheet = as.data.frame(mysampleSheet)
mydba = dba(sampleSheet = mysampleSheet, peakCaller = "raw", peakFormat="raw", bRemoveM = TRUE, bRemoveRandom = TRUE)
plot(mydba)
mydbacount = dba.count(mydba)
plot(mydbacount)
normmydbacount = dba.normalize(mydbacount)
plot(normmydbacount)
normmydbacount2 <- dba.contrast(normmydbacount, reorderMeta=list(Condition="KDM5B_WT"), minMembers = 2)
normmydbacount3 <- dba.analyze(normmydbacount2, bGreylist = FALSE, bBlacklist = FALSE)
dba.show(normmydbacount3, bContrasts=TRUE)
plot(normmydbacount3, contrast=1)
dba.plotVolcano(normmydbacount3)
pdf(file="volcano.pdf")
plot(normmydbacount3, contrast=1)
dba.plotVolcano(normmydbacount3)
dev.off()
results_diffbind <- dba.report(normmydbacount3, method=DBA_DESEQ2, contrast=1, th=1)
diffbind_tab = as.data.frame(results_diffbind)
write.table(diffbind_tab, file="H3K27me3_diffbind.bed", sep="\t", quote=F, row.names=F)
