---
title: "prepping project cell lines for heatmap"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
```

```{r}
pI_tab <- read.delim("C:/Users/kayle/Box/Vertinolab/GenomicSandbox/project_cell_lines/ProSeq/pI/V3/project_cell_lines_pI.txt")
```

```{r}
pI_tab_na_as_0 = pI_tab %>% 
            mutate(pI.MCF7 = replace_na(pI.MCF7, 0),
                   pI.SUM159 = replace_na(pI.SUM159, 0),
                   pI.MCF10A = replace_na(pI.MCF10A, 0),
                   pI.T47D = replace_na(pI.T47D, 0),
                   pI.MB231 = replace_na(pI.MB231, 0)
                   )
```

```{r}
setDT(pI_tab_na_as_0)
T47D_ordered <- pI_tab_na_as_0[pI.T47D!=0,]
No_T47D_ordered <- pI_tab_na_as_0[pI.T47D==0,]
setorder(T47D_ordered, cols = - "pI.T47D")
No_T47D_ordered[, sumcol := (pI.T47D+pI.MCF10A+pI.MCF7+pI.MB231+pI.SUM159)/5]
setorder(No_T47D_ordered, cols = - "sumcol")

MCF10A_ordered <- pI_tab_na_as_0[pI.MCF10A!=0,]
No_MCF10A_ordered <- pI_tab_na_as_0[pI.MCF10A==0,]
setorder(MCF10A_ordered, cols = - "pI.MCF10A")
No_MCF10A_ordered[, sumcol := (pI.T47D+pI.MCF10A+pI.MCF7+pI.MB231+pI.SUM159)/5]
setorder(No_MCF10A_ordered, cols = - "sumcol")

MCF7_ordered <- pI_tab_na_as_0[pI.MCF7!=0,]
No_MCF7_ordered <- pI_tab_na_as_0[pI.MCF7==0,]
setorder(MCF7_ordered, cols = - "pI.T47D")
No_MCF7_ordered[, sumcol := (pI.T47D+pI.MCF10A+pI.MCF7+pI.MB231+pI.SUM159)/5]
setorder(No_MCF7_ordered, cols = - "sumcol")

MB231_ordered <- pI_tab_na_as_0[pI.MB231!=0,]
No_MB231_ordered <- pI_tab_na_as_0[pI.MB231==0,]
setorder(MB231_ordered, cols = - "pI.MB231")
No_MB231_ordered[, sumcol := (pI.T47D+pI.MCF10A+pI.MCF7+pI.MB231+pI.SUM159)/5]
setorder(No_MB231_ordered, cols = - "sumcol")

SUM159_ordered <- pI_tab_na_as_0[pI.SUM159!=0,]
No_SUM159_ordered <- pI_tab_na_as_0[pI.SUM159==0,]
setorder(SUM159_ordered, cols = - "pI.SUM159")
No_SUM159_ordered[, sumcol := (pI.T47D+pI.MCF10A+pI.MCF7+pI.MB231+pI.SUM159)/5]
setorder(No_SUM159_ordered, cols = - "sumcol")
```

```{r}
dim(MCF10A_ordered)
dim(MCF7_ordered)
dim(MB231_ordered)
dim(SUM159_ordered)
dim(T47D_ordered)

dim(No_MCF10A_ordered)
dim(No_MCF7_ordered)
dim(No_MB231_ordered)
dim(No_SUM159_ordered)
dim(No_T47D_ordered)
```


```{r}
write.table(T47D_ordered[,1:6], file="genes_ranked_by_T47D_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(MCF7_ordered[,1:6], file="genes_ranked_by_MCF7_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(MCF10A_ordered[,1:6], file="genes_ranked_by_MCF10A_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(MB231_ordered[,1:6], file="genes_ranked_by_MB231_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(SUM159_ordered[,1:6], file="genes_ranked_by_SUM159_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)

write.table(No_T47D_ordered[,1:6], file="No_T47D_genes_by_avg_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(No_MCF7_ordered[,1:6], file="No_MCF7_genes_by_avg_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(No_MCF10A_ordered[,1:6], file="No_MCF10A_genes_by_avg_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(No_MB231_ordered[,1:6], file="No_MB231_genes_by_avg_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
write.table(No_SUM159_ordered[,1:6], file="No_SUM159_genes_by_avg_pI.bed", quote=FALSE,
            sep="\t", row.names = FALSE, col.names = FALSE)
```

