---
title: "gene_n_CGI_windows"
output: html_notebook
---

```{r}
Gencode39_knowngene_hg38 <- read.delim( "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/Regions/Untouched source data/gencode/Gencode39_knowngene.hg38.txt" )
```
why is knowngene the comprehensive set anyway? looks like it's a historical name scheme I guess.
So honestly for this I just need to preseve the first three columns.
```{r}
library( tidyverse )
dim( Gencode39_knowngene_hg38 )
minimal_set_genes <- Gencode39_knowngene_hg38 |> 
  select( c( 1:3 ) ) |>
  filter( !grepl( 'chrY|chrM|([\\w_]+)alt|random|fix|v1', X.chrom ) ) |> 
  unique()
dim( minimal_set_genes )
```
honestly that's less lost than I thought there would be, but still 30K genes.
```{r}
cgi <- read.delim( "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/Regions/Untouched source data/cpgIsland.hg38.txt.gz", header = FALSE )
```

```{r}
dim( cgi )
minimal_set_cgi <- cgi |> 
  select( c( 1:3 ) ) |>
  filter( !grepl( 'chrY|chrM|([\\w_]+)alt|random|fix|v1', V1 ) ) |> 
  unique()
dim( minimal_set_cgi )
```

```{r}
Refseq_all <- read.delim( "C:/Users/kayle/Box/Vertinolab/McKayla Ford/Data/Regions/Untouched source data/refseq/Refseq_all.hg38.txt.gz" )
```

```{r}
dim( Refseq_all )
minimal_set_refseq <- Refseq_all |> 
  select( c( 3, 5, 6 ) ) |>
  filter( !grepl( 'chrY|chrM|([\\w_]+)alt|random|fix|v1', chrom ) ) |> 
  unique()
dim( minimal_set_refseq )
```

```{r}
cn <- c( "chrom", "start", "end" )
colnames( minimal_set_cgi ) <- cn
colnames( minimal_set_genes ) <- cn
colnames( minimal_set_refseq ) <- cn
minimal_set <- rbind(minimal_set_genes, minimal_set_cgi, minimal_set_refseq )
minimal_set <- minimal_set |> unique()
dim( minimal_set )
```

```{r}
minimal_set$start <- minimal_set$start - 5000
minimal_set$end <- minimal_set$end + 5000
```

```{r}
write.table(
  minimal_set, file = file( "minimal_set.bed", "wb" ), quote=FALSE,
  row.names=FALSE, col.names=FALSE, sep = "\t"
)
```

